### ISSUE TITLE
confuse about the voxel label generating?

### ISSUE THREAD

**Issue by rockywind** [zhouqiu/SOGDet#1]
Hi, thank you for sharing the great work.
I am confused as to why it is necessary to subtract 1.
![image](https://github.com/zhouqiu/SOGDet/assets/14838781/5962d774-7ac4-4c34-9e9f-c777f906fa66)

**Comment by zhouqiu** [comment]
Thank you for your interest in our work. This operation is to avoid ‘index
out of range’ error when using the variable ‘grid_ind’.

Best regards,
Qiu

xiaoquan wang ***@***.***>于2023年12月18日 周一10:38写道：
