### ISSUE TITLE
Question about binary or semantic occupancy label

### ISSUE THREAD

**Issue by Rayn-Wu** [zhouqiu/SOGDet#3]
Hi，thanks for sharing this great project.
I am wondering if you use binary occupancy label for training or just regular semantic label.  
In the paper writes 

> "we consider only the geometry features of each voxel"

but in the code there is an occ learning map(for 18 classes), which makes me feel a little confused.

**Comment by zhouqiu** [comment]
Hi Rayn,

Thank you for your interest in our work.

You should choose only one type of labels (binary or semantic) during a
training process. If you prefer the higher performance on OD task, please
choose semantic labels, which corresponds to ‘sogdet-se-*.py’ in
‘configs/sogdet/‘ of our code.

Best regards,
Qiu

Rayn-Wu ***@***.***>于2024年3月3日 周日10:44写道：

**Comment by Rayn-Wu** [comment]
Thank you for your reply！That solved my confusion.
