### ISSUE TITLE
Question about binary occupancy label

### ISSUE THREAD

**Issue by Rayn-Wu** [zhouqiu/SOGDet#4]
Hi，
When you use **binary label** for supervision, do you calculate the iou of' occupancy' and ' free '？
BTW，did you use Occ3d-nuScenes for the OC branch to get the mIoU results?

**Comment by zhouqiu** [comment]
We did not calculate iou of the binary version. And we did not use Occ3d-nuScenes to get miou.

**Comment by Rayn-Wu** [comment]
Thanks for your reply.
